import type { MetadataRoute } from 'next';

/**
 * PWA manifest — makes iClose installable to the home screen on Android and
 * desktop (and complements the apple-touch-icon for iOS). The wordmark icons
 * live in /public/icons (generated by scripts/gen-pwa-icons.mjs).
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'iClose',
    short_name: 'iClose',
    description: 'Buy, sell and close UAE real estate without paying commission.',
    // Launch straight into the app experience, but keep the whole origin in
    // scope so links out (e.g. /credits) stay inside the installed app.
    start_url: '/experience',
    id: '/experience',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#ffffff',
    theme_color: '#ffffff',
    categories: ['business', 'lifestyle', 'shopping'],
    icons: [
      { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
